package mena.gov.bf.model;

public enum TypeDossier {
    ACTIVITE, LOT, TACHE, ETAPE, DEPOUILLEMENT, RECEPTION, ANALYSE, DELIBERATION, EXECUTION, PENALITE, AVENANT, CONTRAT,
    COMMISSION, TACHEETAPE, PPMACTIVITE, RECLAMATION, CANDIDATCAUTIONLOT, DECISION, STATUTEXECUTION, CONTENTIEUX,
    ETAPEEXECUTION, LIQUIDATION, DECISIONCONTENTIEUX,ORDRESERVICE
}
